name: production-release-pr

on:
  push:
    branches:
      - staging
jobs:
  call-release-pr:
    uses: ./.github/workflows/release-pr.yml
    with:
      from: staging
      to: main
      template: .github/git-pr-release/template.erb


