name: production-release-pr

on:
  push:
    branches:
      - staging
env:
  ENV_NAME: "本番"

jobs:
  call-release-pr:
    uses: ./.github/workflows/release-pr.yml
    with:
      from: staging
      to: main
      template: .github/git-pr-release/shared.erb


