name: release-pr

on:
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string
      template:
        required: true
        type: string
      env_name:
        required: true
        type: string


jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - run: gem install --no-document git-pr-release
      - run: git-pr-release --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ inputs.to}}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ inputs.from }}
          GIT_PR_RELEASE_TEMPLATE: ${{ inputs.template }}
          TZ: Asia/Tokyo
          ENV_NAME: ${{ inputs.env_name }}
